---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ekselmyi/sirute.web/
    - /bin/cp -R sirute $DEPLOYPATH
    # - /bin/cp -R resources $DEPLOYPATH
    #- /bin/cp -R routes $DEPLOYPATH
    # - /bin/cp -R public $DEPLOYPATH
    # - /bin/cp -R vendor $DEPLOYPATH