---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ekselmyi/public_html/blokc.web.id
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R resources $DEPLOYPATH
    - /bin/cp -R routes $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
  