name: cd

on:
  push:
    branches:
      - dev

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy to production using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/diy-projects.my.id/portal-rw.diy-projects.my.id
            php artisan optimize:clear
            export ASDF_DATA_DIR=~/.asdf
            source ~/.asdf/asdf.sh
            git pull origin dev
            npm install
            npm run build
